// NEET syllabus seed (Physics, Chemistry, Botany, Zoology) → class → chapter → topics.
//
// Built from the Edurack "NEET Chapter-wise PYQ Blueprint 2020–2026" PDFs
// (incl. Re-NEET 2026): every chapter and topic tag in those four documents,
// with duplicate chapter spellings merged ("The D and F-Block Elements" +
// "The d and f-Block Elements", "Work Energy and Power" + "Work, Energy and
// Power", ...), near-identical topic tags merged, and the tags the PDFs cut
// off mid-word ("Outbreed…") completed.
//
// Like the JEE seed this is only a *seed*: getSyllabus (server-functions/
// admin.ts) copies it into the `syllabus` collection under NEET_SYLLABUS_KEY
// and the database copy is what every screen reads. Bump NEET_SYLLABUS_VERSION
// to push a new seed over the stored copy.
//
// "Biology" is not stored: a test whose subject is "Biology" reads Botany and
// Zoology together (see chaptersFor in ncert-syllabus.ts).
//
// Anything a question is tagged with that is not in these lists is saved as
// "Out of Syllabus" automatically (see classifySyllabusTag).
import type { Syllabus, SyllabusChapter } from "@/lib/ncert-syllabus";

export const NEET_SYLLABUS_KEY = "neet-default";
export const NEET_SYLLABUS_VERSION = 1;

const ch = (chapter: string, topics: string[], aliases?: string[]): SyllabusChapter =>
  aliases?.length ? { chapter, topics, aliases } : { chapter, topics };

export const NEET_SYLLABUS: Syllabus = {
  Physics: {
    "11": [
      ch("Units and Measurements", [
        "Dimensional Analysis and its Applications (Deducing Relation among Various Physical Quantities)",
        "Dimensional Analysis and its Applications (Finding the Dimensions of Unknowns)",
        "Dimensional Constants",
        "Dimensions of Physical Quantities",
        "Errors in Measurement (Combination of Errors)",
        "Errors in Measurement (Systematic Errors, Random Errors and Gross Error)",
        "Measurement of Length (Measurement of Large Distances and Estimation of very Small Distances)",
        "Measuring Instruments (Least Count of Vernier Callipers)",
        "Measuring Instruments (Reading a Vernier Callipers)",
        "Measuring Instruments (Reading of Screw Gauge)",
        "Significant Figures (Rule to Find Significant Figures or Digit)",
        "Significant Figures (Rules for Arithmetic Operations with Significant Figures)",
      ]),
      ch("Motion in a Straight Line", [
        "Acceleration (Instantaneous Acceleration)",
        "Average Velocity and Average Speed (Average Speed)",
        "Displacement of Particle in nth Second",
        "Equations of Motion (Application of Equations of Motion)",
        "Graphs in Motion in One Dimension (Motion Diagram)",
        "Kinematic Equations for Uniformly Accelerated Motion (Free Fall (Motion under Gravity))",
        "Kinematical Quantities or Graphs (Velocity(v) - Time(t) Graph)",
        "Motion under gravity (Free fall motion) (Calculation of Time of flight, max height, etc.)",
        "Motion under gravity (Free fall motion) (Height to ground projection in upward and downward Direction)",
        "Relative velocity in One Dimension (Relative Velocity (For ex - Two Trains, Police-Thief))",
      ]),
      ch("Motion in a Plane", [
        "Motion in a Plane with Constant Acceleration",
        "Projectile Motion (Analysis of Projectile Motion)",
        "Projectile Motion (Maximum Height of a Projectile)",
      ]),
      ch("Laws of Motion", [
        "Application of Laws of Motion (Various Forces in Nature)",
        "Applications of Friction Force (Problems Involving Frictional Forces)",
        "Friction (Friction as a Contact Force and Friction Constant)",
        "Newton's First Law of Motion (Momentum)",
        "Newton's Second Law of Motion",
        "Newton's Second Law of Motion (Application of Newton's Second Law of Motion)",
        "Newton's Second Law of Motion (Resultant Force)",
      ]),
      ch("Work, Energy and Power", [
        "Calculation of Work (Work Done by Constant Force (Including Work Done by Gravity))",
        "Calculation of Work (Work Done by Variable Force (Work Done by Spring Force))",
        "Power (Average Power)",
        "Power (Definition)",
        "Power (Efficiency)",
        "Power (Instantaneous power)",
        "The Concept of Potential Energy (PE in Case of Spring)",
      ]),
      ch("Center of Mass and System of Particles", [
        "Centre of Mass (Centre of Mass of Uniform Laminar Objects, Centre of Mass of Rigid Continuous Bodies) (Centre of Mass of Two Bodies System)",
        "Collisions (Collision in One Dimensions)",
        "Collisions (Elastic Collision)",
        "Collisions (Inelastic Collision)",
        "Conservation of Momentum, Common Forces in Mechanics (Applications of Law of Conservation of Linear Momentum)",
      ], ["Centre of Mass and System of Particles"]),
      ch("Rotational Motion", [
        "Analogue of Newton's Second law of Motion for Pure Rotation",
        "Angular Momentum (Angular Momentum of a Rigid Body Rotating about a Fixed Axis)",
        "Equilibrium of a Rigid Body (Principle of Moments)",
        "Kinematics of Rotational Motion (Equations of Rotational Motion)",
        "Moment of Inertia (Method of Calculation of Moment of Inertia) (Circular Ring, Uniform Circular Disc, etc.)",
        "Moment of Inertia (Moment of Inertia of a Uniform Rectangular Lamina)",
        "Moment of Inertia (Moment of Inertia of Some Important Cases)",
        "Moment of Inertia (Radius of Gyration)",
        "Rolling Motion (Pure Rolling on a Horizontal Plane)",
        "Torque and Angular Momentum (Conservation of Angular Momentum)",
        "Torque and Angular Momentum (Torque of a Force About a Point)",
      ]),
      ch("Circular Motion", [
        "Dynamics of Circular Motion (Banking of Roads without Friction)",
        "Dynamics of Circular Motion (Circular Motion)",
        "Non-Uniform Circular Motion",
        "Uniform Circular Motion (Expression for Centripetal Acceleration, Angular Displacement, Angular Speed, Time Period, and Frequency)",
        "Vertical Circular Motion",
      ]),
      ch("Gravitation", [
        "Acceleration Due to Gravity (Variation in Acceleration Due to Gravity by Mass and Depth)",
        "Acceleration Due to Gravity (Variation in Acceleration Due to Gravity Due to Height)",
        "Earth Satellite, Energy of an Orbiting Satellite (Geostationary and Polar Satellites) (Earth Satellite)",
        "Escape Speed or Escape Energy (Escape Speed)",
        "Gravitational Field (Gravitational Field Due to Bodies of Different Shapes)",
        "Gravitational Field and its Intensity (Gravitational Field Intensity Due to a Particle (Point Mass))",
        "Gravitational Potential Energy (Relation Between Gravitational Field and Potential)",
        "Kepler's Laws (Law of Periods)",
        "Satellite Motion (Time Period of a Satellite)",
      ]),
      ch("Mechanical Properties of Solids", [
        "Hooke's Law",
        "Stress and Strain (Tensile and Compressive Strain)",
        "Types of Elasticity Coefficients (Elastic Moduli) (Bulk Modulus)",
        "Types of Elasticity Coefficients (Elastic Moduli) (Determination of Young's Modulus of the Material of a Wire)",
        "Types of Elasticity Coefficients (Elastic Moduli) (Shear Modulus or Modulus of Rigidity)",
      ]),
      ch("Mechanical Properties of Fluids", [
        "Bernoulli's Equation (Pitot Tube)",
        "Bernoulli's Principle (Applications of Bernoulli's Theorem)",
        "Pressure (Absolute Pressure)",
        "Surface Tension",
        "Surface Tension (Bubbles Excess Pressure)",
        "Surface Tension (Capillary Rise)",
        "Surface Tension (Surface Energy)",
        "Viscosity (Terminal Velocity)",
      ]),
      ch("Thermal Properties of Matter", [
        "Calorimetry (Principle Of Calorimetry)",
        "Heat Transfer (Conduction)",
        "Thermal Expansion (Volume Expansion)",
      ]),
      ch("Thermodynamics", [
        "Calculation of Work (Work Done in P-V Curve)",
        "Carnot's Engine",
        "First law of Thermodynamics",
        "Internal Energy (Internal Energy and its Change)",
        "Thermodynamic Processes (Adiabatic Process)",
        "Thermodynamic Processes (Cyclic Process)",
        "Thermodynamic State Variables",
      ]),
      ch("Kinetic Theory", [
        "Behaviour of Gases (Charles Law)",
        "Behaviour of Gases (Ideal Gas Equation)",
        "Kinetic Theory of an Ideal Gas",
        "Kinetic Theory of an Ideal Gas (Average Kinetic Energy of a Gas Molecule)",
        "Kinetic Theory of an Ideal Gas (Mean Square Speed)",
        "Kinetic Theory of an Ideal Gas (RMS Speed)",
        "Mean Free Path",
        "Specific Heat Capacity (Molar Specific Heat of Monatomic Gas, Diatomic Gas)",
      ]),
      ch("Oscillations", [
        "Energy in Simple Harmonic Motion",
        "Simple Harmonic Motion (Phase (φ))",
        "Simple Harmonic Motion (Time Period and Frequency)",
        "Some Systems Executing Simple Harmonic Motion (Oscillations Due to a Spring)",
        "Some Systems Executing Simple Harmonic Motion (SHM of Floating Body)",
        "Some Systems Executing Simple Harmonic Motion (The Simple Pendulum)",
        "Velocity and Acceleration in Simple Harmonic Motion",
      ]),
      ch("Waves", [
        "Beats",
        "Sinusoidal Progressive Waves (Amplitude, Phase, etc.)",
        "Standing or Stationary Waves (Standing Waves and Normal Modes in Open Organ Pipe)",
        "String Waves (Speed of Transverse Wave on a Stretched String)",
      ]),
    ],
    "12": [
      ch("Electric Charges and Fields", [
        "Charging Methods (Charging by Induction, Friction and Conduction)",
        "Dipole in a Non Uniform External Field (Force and Torque on a Finite Dipole)",
        "Electric Dipole (For Points on the Axis)",
        "Electric Field",
        "Electric Field (Electric Field Due to Point Charge and a System of Charges)",
        "Electric Flux",
      ]),
      ch("Electrostatic Potential and Capacitance", [
        "Capacitors and Capacitance (Capacitors and Their Types and Their Capacitance)",
        "Combination of Capacitors (Series Grouping, Parallel Grouping)",
        "Effect of Dielectric on Capacitance",
        "Electrostatic Potential (Electrostatic Potential and Potential Difference)",
        "Electrostatic Potential (Work Done to Move a Charge in Electrostatic Field)",
        "Electrostatics of Conductors (A Conductor Placed in Electric Field)",
        "Electrostatics of Conductors (Important Points about Electrostatics of Conductors)",
        "Energy Stored in a Capacitor (Energy Stored in a Capacitor and Energy Density in Electric Field)",
        "Equipotential Surfaces (Relation Between Electric Field and Potential)",
        "Potential Due to a Continuous Charge Distribution (Potential Due to a Spherical Shell)",
        "Potential Due to a Continuous Charge Distribution (Potential Due to a Uniformly Charged Sphere)",
        "Potential due to a Point Charge & Electric Dipole",
        "Potential due to a Point Charge and Electric Dipole (Potential Due to Dipole at Longitudinal or End-on Position)",
        "Potential Energy in an External Field (Potential Energy of a Dipole in an External Field)",
        "Sharing of Charge and Common PPotential (Sharing of Charge and Common Potential)",
        "Work Done to Move a Electric Dipole in a Electrostatic Field and Potential Energy of an Electric Dipole in a Uniform Electric Field",
      ]),
      ch("Current Electricity", [
        "Ammeter (Conversion of Galvanometer into Ammeter)",
        "Battery (Cell) (Relation between EMF, Internal Resistance, etc.)",
        "Combination of resistors (Combination of Resistors: Series and Parallel)",
        "Combination of resistors (Voltage Division and Current Division Rule)",
        "Current Density",
        "Electric Current (Drift Velocity)",
        "Electric Current (Equation of Current)",
        "Electric Current (Mobility)",
        "Electrical Energy, Power",
        "Electrical Energy, Power (Rating of Electrical Appliances)",
        "Electrical Resistance in Conductors (Colour Coding of Resistances)",
        "Electrical Resistance in Conductors (Resistivity & Conductivity)",
        "Electrical Resistance in Conductors (Temperature Dependence of Resistance & Resistivity)",
        "EMF of Cell (Finding of Equivalent EMF and Internal Resistance of Cells)",
        "Equivalent Resistance (Equivalent Resistance of a Complex Circuits)",
        "Heating Effect of Current",
        "Kirchhoff's Rules (Kirchhoff's Voltage Law: Loop Rule)",
        "Meter Bridge",
        "Miscellaneous",
        "Potentiometer (Application of Potentiometer) (Comparison of Cells, Finding EMF of Unknown Resistance)",
        "Wheatstone Bridge",
      ]),
      ch("Moving Charges and Magnetism", [
        "Ampere's Circuital Law (Magnetic Field Inside a Long Straight Current Carrying Wire)",
        "Current Loop as a Magnetic Dipole",
        "Force between Two Parallel Currents",
        "Magnetic Field at Centre of a Circular Current Carrying Arc",
        "Magnetic Field Due to a Current Element: Biot-Savart Law",
        "Magnetic Field due to Various Current Carrying Conductors (Magnetic Field Surrounding a Thin Straight Current Carrying Conductor)",
        "Magnetic Force (Direction of Magnetic Force, Properties of Magnetic Force)",
        "Magnetic Force on a Current-Carrying Conductor (Effective Length Concept)",
        "Motion in Combined Electric and Magnetic Fields (Velocity Selector, the Cyclotron)",
        "The Solenoid and the Toroid (Solenoid)",
      ]),
      ch("Magnetism and Matter", [
        "Bar Magnet (Angular SHM, Tangent Law)",
        "Bar Magnet (Magnetic Dipole Moment of a Bar Magnet, Magnetic Field)",
        "Bar Magnet (Magnetic Field Lines)",
        "Magnetic Properties of Materials (Diamagnetism, Paramagnetism, etc.)",
        "Magnetisation and Magnetic Intensity (Magnetic Permeability (μ), Relative Permeability (μr))",
        "Magnetisation and Magnetic Intensity (Magnetic Susceptibility (χ))",
        "Magnetism and Gauss's Law",
      ]),
      ch("Electromagnetic Induction", [
        "Combination of Inductors (Series and Parallel Combination)",
        "Faraday's Law of Induction (Lenz's Law, Methods to Change the Magnetic Flux)",
        "Inductor in Circuit (Energy Stored in an Inductor)",
        "Magnetic Flux",
        "Motional Electromotive Force (Motional EMF in a Straight Conductor)",
        "Mutual Inductance (Mutual Inductance of Coaxial Solenoids)",
        "Self Induction (Self Inductance of Solenoid)",
        "Self Induction (Self-Inductance)",
      ]),
      ch("Alternating Current", [
        "Ac Voltage Applied to a Capacitor (Reactance of Capacitive Circuit)",
        "AC Voltage Applied to a Series LCR Circuit",
        "AC Voltage Applied to a Series LCR Circuit (Phase Relationship Between V and I)",
        "AC Voltage Applied to a Series LCR Circuit (Resonance in Series LCR Circuit)",
        "AC Voltage Applied to a Series LCR Circuit (Variation of Impedance with Frequency of Source)",
        "AC Voltage Applied to an Inductor and a Capacitor",
        "Alternating Current and EMF (Peak Value of AC Voltage and Current)",
        "Alternating Current and EMF (Root Mean Square (RMS) Value of Full and Half Cycle)",
        "Power in AC Circuits: the Power Factor",
        "Power in AC Circuits: the Power Factor (Average and Instantaneous Power in AC Circuits)",
        "Transformers",
      ]),
      ch("Electromagnetic Waves", [
        "Displacement Current (Consequences of Displacement Current)",
        "Electromagnetic Spectrum (Microwaves)",
        "Electromagnetic Spectrum (Radio Waves)",
        "Important Characteristics and Nature of Electromagnetic Waves",
        "Intensity of Electromagnetic Wave",
        "Relation Between Electric Field, Magnetic Field and Speed of Light",
        "Sources of Electromagnetic Waves (Important Characteristic and Nature of Electromagnetic Waves)",
      ]),
      ch("Ray Optics and Optical Instruments", [
        "Critical Angle, Grazing Emergence",
        "Dispersion by a Prism (Dispersion) (Angular Dispersion)",
        "Lens Formula (Deriving the Lens Formula)",
        "Optical Instruments (Astronomical Telescope)",
        "Optical Instruments (Simple Microscope and Compound Microscope)",
        "Optical Instruments (Telescope, Terrestrial Telescope)",
        "Refraction (Apparent Depth and Apparent Height)",
        "Refraction (Refraction through a Glass Slab)",
        "Refraction by Lenses (Combination of a Lens and a Mirror)",
        "Refraction by Lenses (Combination of Thin Lenses in Contact)",
        "Refraction by Lenses (Images Formed by a Convex Lens and Images Formed by a Concave Lens)",
        "Refraction through a Prism (Condition for Minimum Deviation)",
        "Refraction through a Prism (Derivation of Refractive Index of Material of Prism)",
        "Thin Lenses",
        "Total Internal Reflection in Nature and its Technological Application",
      ]),
      ch("Wave Optics", [
        "Coherent and Incoherent Sources of Light (Superposition of the Waves, Interference, And Energy Conservation)",
        "Interference of Light Wave and Young's Double Slit Experiment (YDSE)",
        "Interference of Light Wave and Young's Double Slit Experiment (YDSE) (Positions of Fringes on Screen)",
        "Polarisation (Polarisation by Reflection (Brewster's Law))",
        "YDSE (Fringe Width)",
        "YDSE (Young's Double Slit Experiment (Alternate Method))",
      ]),
      ch("Dual Nature of Radiation and Matter", [
        "Einstein's Photoelectric Equation: Energy Quantum of Radiation",
        "Experimental Study of Photoelectric Effect (Effect of Intensity of Light on Photocurrent)",
        "Experimental Study of Photoelectric Effect (Laws of Photoelectric Emission)",
        "Experimental Study of Photoelectric Effect (Threshold Frequency and Wavelength)",
        "Particle Nature of Light: the Photon",
        "Photoelectric Effect (Hertz's Observations, Hallwachs and Lenard's Observations)",
        "Wave Nature of Matter (De Broglie Wavelength of a Moving Particle)",
      ]),
      ch("Atoms", [
        "Alpha-Particle Scattering and Rutherford's Nuclear Model of Atom",
        "Bohr Model of the Hydrogen Atom (Energy of Electron in nth Orbit of Hydrogen Atom)",
        "Bohr Model of the Hydrogen Atom (Failure of Bohr's Theory)",
        "Bohr Model of the Hydrogen Atom (Radius of Electron in nth Orbit of Hydrogen Atom)",
        "Bohr Model of the Hydrogen Atom (Velocity of Electron in Nth Orbit of Hydrogen Atom)",
        "Bohr's Atomic Model (Radius of Electron in nth Orbit of Single Electron Species)",
        "de-Broglie's Explanation of Bohr's Second Postulate of Quantization",
        "The Line Spectra of the Hydrogen Atom, Hydrogen Spectrum (Hydrogen Spectrum)",
        "Thomson Model (Thomson Model, Different Models of Hydrogen)",
        "X-Rays and Atomic Number (Properties of X-rays)",
      ]),
      ch("Nuclei", [
        "Atomic Masses and Composition of Nucleus (Composition of Nucleus: Nuclei are Composed of Protons and Neutrons)",
        "Atomic Masses and Composition of Nucleus (Electron Volt (eV))",
        "Mass-Energy and Nuclear Binding Energy",
        "Nuclear Energy (Chain Reaction)",
        "Nuclear Energy (Fission)",
        "Radioactivity (Alpha Decay and Beta Decay)",
        "Radioactivity (Half-Life and Mean-Life)",
        "Radioactivity (Q-Value in Radioactive Decays)",
        "Size of the Nucleus (Nuclear Density)",
      ]),
      ch("Semiconductor Electronics: Materials, Devices and Simple Circuits", [
        "Application of Junction Diode as a Rectifier (Half-Wave Rectifier Circuit, and Full-Wave Rectifier Circuit)",
        "Digital Electronics and Logic Gates (Combination of Gates)",
        "Digital Electronics and Logic Gates (Logic Gates)",
        "Junction Transistor (Basic Transistor Circuit Configurations and Transistor Characteristics)",
        "P-n Junction (p-n Junction Formation)",
        "Photo Diode, LED, and Solar Cell",
        "Semiconductor Diode",
        "Semiconductor Diode (Circuit Symbol for a p-n Junction Diode)",
        "Semiconductor Diode (P-n Junction under Forward Bias, p-n Junction Diode)",
        "Semiconductor Diode (Voltage Current (V-I) Characteristics of Junction Diode)",
        "Special Purpose p-n Junction Diodes (Zener Diode as a Voltage Regulator)",
      ], ["Semiconductor Electronics"]),
    ],
  },
  Chemistry: {
    "11": [
      ch("Some Basic Concepts of Chemistry", [
        "Atoms and Molecules",
        "Concentration Terms & Application (Molality (m))",
        "Dalton's Atomic Theory",
        "Empirical and Molecular formula",
        "Formula Mass",
        "Miscellaneous (Other Gas Equations)",
        "Mole",
        "Mole Concept and Molar Masses (Mole Concept)",
        "Stoichiometry and Stoichiometric Calculations (Limiting Reagent)",
        "Titration (Simple Titration)",
        "Uncertainty in Measurement (Significant Figures)",
      ]),
      ch("Structure of Atom", [
        "Bohr's Model for Hydrogen Atom (Energy of Electron)",
        "Bohr's Model for Hydrogen Atom (Explanation of Line Spectrum of Hydrogen)",
        "Bohr's Model for Hydrogen Atom (Limitations of Bohr's Model)",
        "Bohr's Model for Hydrogen Atom (Radius of Shell)",
        "Isoelectronic Species",
        "Particle Nature of Electromagnetic Radiation: Planck’s Quantum (Planck’s Quantum Theory)",
        "Quantum Mechanical Model of the Atom (Concept of Orbitals)",
        "Quantum Mechanical Model of the Atom (Quantum Number)",
        "Quantum Mechanical Model of the Atom (Radial and Angular Nodes)",
        "Quantum Number (Principal Quantum Number)",
      ]),
      ch("Classification of Elements and Periodicity in Properties", [
        "Classification of Elements as Metals, Non-Metals and Metalloids",
        "Effective Nuclear Charge",
        "Electronic Configuration of Elements and The Periodic Table (Groupwise Electronic Configuration)",
        "Nomenclature of Elements With Atomic Number > 100",
        "Periodic Properties (Electron Affinity)",
        "Periodic Properties (Electronegativity)",
        "Periodic Properties (Ionization Energy (Enthalpy))",
      ]),
      ch("Chemical Bonding and Molecular Structure", [
        "Bond Parameters (Bond Energy)",
        "Bond Parameters (Bond order)",
        "Dipole Moment",
        "Dipole Moment (Applications of Dipole moment)",
        "Formal Charge (Formal Charge and its Applications)",
        "Hybridisation (Types of Hybridization by Using s and p Orbitals)",
        "Hydrogen Bonds (Types of Hydrogen Bonds)",
        "Kossel - Lewis Approach to Chemical Bonding (Covalent Bonds)",
        "Kössel - Lewis Approach to Chemical Bonding (Limitation of Octet Rule)",
        "Molecular Orbital Theory (MOT)",
        "Valence Shell Electron Pair Repulsion (VSEPR) Theory (Postulates, Applications and Limitations of VSEPR Theory)",
      ]),
      ch("Thermodynamics", [
        "Change in Thermodynamics Properties in Expansion or Contraction of a Gas",
        "Enthalpy Change (Standard Enthalpy of Formation (ΔH°f))",
        "Enthalpy Change (Thermochemical Equations)",
        "Gibbs Energy Change and Equilibrium",
        "Gibbs Energy Change and Non-Mechanical Work",
        "Internal Energy",
        "Measurement of dU and dH: Bomb Calorimeter (dH Measurements)",
        "Pressure-Volume Work",
        "Relationship Between Cp and Cv (Relationship Between Heat of Reaction at Constant Pressure)",
        "Spontaneity: Second Law of Thermodynamics (Entropy and Spontaneity)",
        "Spontaneity: Second Law of Thermodynamics (Entropy for Different Processes)",
        "Spontaneity: Second Law of Thermodynamics (Entropy)",
        "Thermodynamic Processes (Adiabatic Process)",
        "Thermodynamic Processes (Isothermal Process)",
        "Work",
      ]),
      ch("Equilibrium", [
        "Acid - Base Titration (Titration Curves for Weak Acid Vs Strong Base)",
        "Acids, Bases and Salts (Arrhenius concept of Acids and Bases)",
        "Acids, Bases and Salts (Lewis Acid and Bases)",
        "Applications of Equilibrium Constant (Problems involving Kc)",
        "Applications of Equilibrium Constant (Relationship Between Kp and Kc)",
        "Applications of Solubility (Effect of Complex Formation and Hydrolysis on Solubility)",
        "Buffer Solution",
        "Equilibrium in Chemical Process (Characteristics of Equilibrium Constant)",
        "Equilibrium in Chemical Process (Chemical Equilibrium)",
        "Ionization of Acids and Bases (Ionization Constant of Acids and Bases)",
        "Le Chatelier's Principle (Effect of Concentration Change)",
        "pH Calculation (pH of Weak Acid)",
        "Relationship Between Equilibrium Constant (K), Reaction Quotient (Q) and Gibbs Free Energy (G)",
        "Solubility Equilibria of Sparingly Soluble Salts (Constant of Solubility Product (Ksp))",
        "Solubility Equilibria of Sparingly Soluble Salts (Relation between Solubility (S) And Solubility Product)",
      ]),
      ch("Redox Reactions", [
        "Balancing of Redox Reactions (Balancing Equation by Oxidation Number Method)",
        "Oxidation Number",
        "Oxidation Number (Oxidation and Reduction in Terms of Oxidation Number)",
        "Oxidation Number and Nomenclature (Oxidation State of Element in Periodic Table)",
        "Redox Reactions as the Basis of Titration (Potassium Permanganate (KMnO₄))",
        "Types of Redox Reactions (Displacement Reactions)",
      ]),
      ch("Organic Chemistry: Some Basic Principles and Techniques", [
        "Aromaticity (Non-Benzenoid System)",
        "General Introduction (Hybridization in Carbon Compounds)",
        "Hyperconjugation (Hyperconjugation and its Applications)",
        "Methods of Purification of Organic Compounds (Chromatography)",
        "Methods of Purification of Organic Compounds (Distillation)",
        "Methods of Purification of Organic Compounds (Distillation- Fractional Distillation)",
        "Methods of Purification of Organic Compounds (Sublimation)",
        "Nomenclature of Organic Compounds (I.U.P.A.C System of Nomenclature)",
        "Qualitative Analysis of Organic Compounds (Estimation of Nitrogen (Kjeldahl's Method))",
        "Qualitative Analysis of Organic Compounds (Test for Nitrogen, Sulphur and Halogens (Lassaigne's Test))",
        "Reaction Intermediates (Carbocation)",
        "Stereoisomerism (Geometrical Isomerism)",
        "Types of Isomerism (Structural Isomerism, Stereoisomerism)",
      ]),
      ch("Hydrocarbons", [
        "Alkanes (Chemical Reactions of Alkanes)",
        "Alkanes (Conformations)",
        "Aromatic Hydrocarbon (Aromaticity)",
        "Aromatic Hydrocarbon (Physical and Chemical Properties)",
        "Chemical Reaction of Alkanes (Controlled Oxidation)",
        "Chemical Reaction of Alkenes (By KMnO₄)",
        "Chemical Reaction of Alkynes (Reduction by Lindlar's Catalyst)",
        "Classification",
        "General Characteristics of Alkanes (Physical Properties of Alkanes)",
        "General Characteristics of Alkenes (Chemical Properties)",
        "General Characteristics of Alkenes (Tests of Unsaturation)",
        "Preparation of Alkanes",
        "Preparation of Alkenes (Preparation Methods)",
      ]),
      ch("States of Matter", [
        "Dalton's Law of Partial Pressures",
        "Ideal Gas Equation",
        "The Gas Laws (Boyle's Law (Pressure-Volume Relationship))",
        "Thermal Energy - Intermolecular Forces versus Thermal Energy (Intermolecular Forces)",
      ]),
      ch("Hydrogen", [
        "Hydrogen Peroxide (H2O₂) (Structure)",
        "Various Forms of Hydrogen (Atomic Hydrogen)",
        "Water (H₂O) (Chemical Properties)",
        "Water (H₂O) (Degree of Hardness of Water)",
      ]),
      ch("The s-Block Elements", [
        "Alkali Metal (Atomic Properties)",
        "Alkali Metal (Chemical Properties)",
        "Biological Importance of Magnesium and Calcium",
        "General Characteristics of the Compounds of the Alkali Metals (Oxides and Hydroxides)",
        "Group - 2 Elements: Alkaline Earth Metals (Anomalous Behaviour of Beryllium)",
        "Group - 2 Elements: Alkaline Earth Metals (Chemical Properties)",
        "Group - 2 Elements: Alkaline Earth Metals (Uses of Alkaline Earth Metals)",
      ]),
      ch("The p-Block Elements (Group 13 and 14)", [
        "Allotropes of Carbon (Crystalline Form (1) Diamond)",
        "Allotropes of Carbon and Uses (Amorphous Form)",
        "Aluminium Compounds",
        "Compounds of Carbon (Carbon Monoxide)",
        "General Characteristics of P-Block Elements",
        "Group 13 Elements: The Boron Family (General Trends in Atomic and Physical Properties)",
        "Some Important Compounds of Aluminium (Aluminium Oxide or Alumina, Al₂O₃)",
        "Some Important Compounds of Boron (Boron Halide)",
        "Some Important Compounds of Boron (Hydrides of Boron (Diborane))",
      ], ["The p-Block Elements"]),
      ch("Environmental Chemistry", [
        "Environmental Pollution (Pollutants and Contaminant)",
        "Gaseous Air Pollutants (Oxides of Sulphur)",
        "Green House Effect",
      ]),
      ch("Principles of Qualitative Analysis", [
        "Analysis of Basic Radicals (Group - Vi)",
        "Introduction",
        "Test of Cations (Flame Test on Dry Samples)",
      ]),
    ],
    "12": [
      ch("The Solid State", [
        "Calculations for Unit Cell Dimensions (Density of Unit Cell)",
        "Calculations for Unit Cell Dimensions (Radius Ratio)",
        "Close Packed Structures (Close Packing in Three Dimension)",
        "Crystal Lattice or Space Lattice",
        "Imperfections or Defects in Solids (Point Defects in Stoichiometric Crystals)",
        "Voids",
      ]),
      ch("Solutions", [
        "Binary Solution (Solute and Solvent, Types of Solutions)",
        "Colligative Properties (Depression in Freezing Point)",
        "Colligative Properties (Elevation of Boiling Point)",
        "Colligative Properties (Osmosis and Osmotic Pressure)",
        "Concentration Terms (Molality (M))",
        "Ideal and Non-ideal Solutions (Ideal Solution and Non Ideal Solutions)",
        "Solubility (Henry's Law)",
        "Solubility (Solubility of a Gas in a Liquid)",
        "Vapour Pressure of Liquid Solutions (Raoult’s Law)",
        "Vapour Pressure of Liquid Solutions (Vapour Pressure of Liquid-Liquid Solutions)",
      ]),
      ch("Electrochemistry", [
        "Determination of Cell Constant",
        "Electrochemical Cell (Electrode Potential and EMF of a Cell)",
        "Electrochemical Series (Electrochemical Series and Applications)",
        "Electrolysis (Mechanism and Product of Electrolysis)",
        "Kohlrausch's Law",
        "Measurement of Conductance and Conductivity of Ionic Solutions",
        "Molar Conductivity",
        "Nernst Equation",
        "Quantitative Aspects of Electrolysis and Faraday's Laws (Faraday's First Law of Electrolysis)",
      ]),
      ch("Chemical Kinetics", [
        "Activated Complex Theory",
        "Activation Energy",
        "Applications of Radioactivity (In Industries)",
        "Collision Theory of Chemical Reactions",
        "Experimental Determination of Order of Reaction (Initial Rate Method)",
        "Integrated Rate Equations (First Order Reaction)",
        "Integrated Rate Equations (Half Life Period of a Reaction)",
        "Integrated Rate Equations (Nth Order of Reaction)",
        "Integrated Rate Equations (Zero Order Reaction)",
        "Numericals on Some Important First Order Reactions",
        "Order and Molecularity of Reaction",
        "Potential Energy Curve (Endothermic and Exothermic Reactions)",
        "Rate constant",
        "Rate constant (Characteristics of Rate Constant)",
        "Ratio of Two Rate Constant at Two Different Temperatures",
        "Temperature Dependence of the Rate of a Reaction (Arrhenius Equation)",
      ]),
      ch("Surface Chemistry", [
        "Colloids (Application of Colloids)",
        "Colloids (Coagulation of Lyophobic Sol, Mutual Coagulation, etc.)",
        "Colloids (Protection of Colloids)",
        "Emulsions",
      ]),
      ch("General Principles and Processes of Isolation of Elements", [
        "Electrochemical Principles of Metallurgy (Extraction of Aluminium (Electrometallurgy))",
        "Extraction of Copper",
        "Extraction of Iron",
        "Extraction of Metals and Non-Metals (General) (Pulverisation)",
        "Modes of Occurrence of Metals (Classification of Ores (Native Ore and Combined Ore))",
      ]),
      ch("The p-Block Elements (Group 15 to 18)", [
        "Chemistry of Noble Gas Compounds (Structure and Properties)",
        "Group 15 Elements (Chemical Properties)",
        "Group 15 Elements (Reactivity towards hydrogen)",
        "Group 16 Elements (Atomic and Physical Properties)",
        "Group 16 Elements (Oxidation State)",
        "Group 16 Elements (Reactivity towards hydrogen)",
        "Group 17 Elements (Chemical Properties)",
        "Group 18 Elements (Occurrence)",
        "Interhalogen Compounds (Chemical Properties)",
        "Oxides (Classification of Oxides Based on Chemical Behaviour)",
        "Oxoacids of Sulphur",
      ], ["The p-Block Elements (XII)"]),
      ch("The d and f-Block Elements", [
        "Chemical Properties",
        "General Characteristics and Comparison with Lanthanides (General Characteristics and Comparison with Lanthanoids)",
        "General Properties of Transition Elements (D-Block) (Alloy Formation)",
        "General Properties of Transition Elements (D-Block) (Catalytic Properties)",
        "General Properties of Transition Elements (D-Block) (Formation of Complex Compounds)",
        "General Properties of Transition Elements (D-Block) (Magnetic Properties)",
        "General Properties of Transition Elements (D-Block) (Melting and Boiling Points)",
        "General Properties of Transition Elements (D-Block) (Trends in the M3+/M2+ standard electrode potentials)",
        "Some Applications of d and f-Block Elements",
        "Some Important Compounds of Transition Elements (Potassium Permanganate (KMnO₄))",
        "The Inner Transition Elements",
        "The Lanthanides (Electronic Configuration and Classification)",
        "The Lanthanides (Oxidation State)",
      ]),
      ch("Coordination Compounds", [
        "Bonding in Coordination Compounds (Crystal Field Theory (CFT))",
        "Bonding in Coordination Compounds (Magnetic Properties of Coordination Compounds)",
        "Bonding in Coordination Compounds (Valence Bond Theory (VBT))",
        "Chelation and Denticity",
        "Coordination Compounds",
        "Coordination Compounds (Homoleptic and Heteroleptic Complexes)",
        "Definitions of Some Important Terms Pertaining to Coordination Compounds (Coordination Entity and Counter Ion, Central Atom/Ion)",
        "Definitions of Some Important Terms Pertaining to Coordination Compounds (Ligand)",
        "Isomerism in Coordination Compounds (Stereoisomerism)",
        "Isomerism in Coordination Compounds (Structural Isomerism)",
        "Ligand Field Theory (π-Bonding and Sigma Bonding in Octahedral Complexes)",
        "Magnetism",
        "Nomenclature of Coordination Compounds (Nomenclature: IUPAC name of Coordination Compounds)",
        "Stability of Coordination Compounds",
        "Substitution Reaction in Octahedral Complexes",
        "Uses of Metal Catalyst",
        "Werner's Theory of Coordination Compounds (Main Postulates of Werner's Theory, Failure of Werner's Theory)",
      ]),
      ch("Haloalkanes and Haloarenes", [
        "Chemical Properties",
        "Classification",
        "Haloalkanes (Preparation Method)",
        "Haloarenes (Preparation Method)",
        "Isomerism (Introduction)",
        "Nature of C-X Bond",
        "Preparation Method of Haloalkanes (From Alcohols)",
        "Reaction of Haloarenes (Electrophilic Aromatic Substitution Reactions)",
        "Stereochemical Aspects of Nucleophilic Substitution Reactions (Elements of Symmetry and Mechanism)",
      ]),
      ch("Alcohols, Phenols and Ethers", [
        "Alcohols (Chemical Properties)",
        "Alcohols (Physical Properties)",
        "Alcohols (Preparation of Alcohols)",
        "Ethers (Chemical Properties)",
        "Ethers (Structure of Ether)",
        "Phenols (Chemical Properties)",
        "Phenols (Tests for Phenols)",
      ]),
      ch("Aldehydes, Ketones and Carboxylic Acids", [
        "Aldehydes (Methods of Preparation)",
        "Carboxyl Group (Chemical Properties)",
        "Carboxyl Group (Methods of Preparation)",
        "Chemical Reactions of Aldehydes and Ketones (Addition of Grignard Reagent)",
        "Chemical Reactions of Aldehydes and Ketones (Addition of Hydrogen Cyanide)",
        "Chemical Reactions of Aldehydes and Ketones (Nucleophilic Addition Reactions)",
        "Chemical Reactions of Aldehydes and Ketones (Other Reactions)",
        "Chemical Reactions of Aldehydes and Ketones (Oxidation and Reduction of Aldehydes)",
        "Chemical Reactions of Aldehydes and Ketones (Oxidation by Fehling's solution)",
        "Chemical Reactions of Aldehydes and Ketones (Oxidation by Tollen's Reagent)",
        "Chemical Reactions of Aldehydes and Ketones (Oxidation of Methyl Ketones by Haloform Reaction)",
        "Chemical Reactions of Aldehydes and Ketones (Oxidation)",
        "Chemical Reactions of Aldehydes and Ketones (Reaction Due to Presence of Alpha Hydrogen - Aldol/Cross Aldol Condensation)",
        "Chemical Reactions of Aldehydes and Ketones (Reduction Reactions)",
        "Methods of Preparation for Aldehydes and Ketones (From Carboxylic Acids)",
        "Methods of Preparation for Aldehydes and Ketones (From Hydrocarbons)",
        "Miscellaneous/Mixed Reactions",
        "Physical Properties of Aldehydes and Ketones",
      ]),
      ch("Amines", [
        "Aniline (Chemical Properties)",
        "Chemical Reactions",
        "Chemical Reactions (Basic Character of Amines)",
        "Chemical Reactions (Carbylamine Reaction (Isocyanide Test))",
        "Chemical Reactions (Reaction with Aryl Sulphonyl Chloride)",
        "Chemical Reactions (Reaction with Grignard Reagent)",
        "Chemical Reactions (Reaction with Nitrous Acid)",
        "Diazonium Salts (Chemical Reactions)",
        "Preparation of Amines",
        "Preparation of Amines (Hofmann Bromamide Degradation Reaction)",
        "Preparation of Amines (Reduction of Nitriles)",
        "Preparation of Amines (Reduction of Nitro Compounds)",
      ]),
      ch("Biomolecules", [
        "Disaccharides (Properties)",
        "Enzymes (Application of Enzymes)",
        "Monosaccharides (Introduction)",
        "Nucleic Acid (Chemical Composition of Nucleic Acids)",
        "Nucleic Acids (Structure of Nucleic Acids)",
        "Properties of Glucose (Chemical Properties of Glucose)",
        "Proteins (Amino Acids)",
        "Proteins (Classification of Amino Acids)",
        "Proteins (Introduction)",
        "Vitamins (Important Vitamins, their Sources and Deficiency Diseases)",
        "Vitamins (Introduction and Classification of Vitamins)",
      ]),
      ch("Polymers", [
        "Classification of Polymers (Classification Based on Molecular Forces)",
        "Classification of Polymers (Classification Based on Source)",
        "Types of Polymerisation Reactions (Addition Polymerisation or Chain Growth Polymerisation)",
      ]),
      ch("Chemistry in Everyday Life", [
        "Drugs and their Classification (On the Basis of Chemical Structure)",
        "Drugs and their Classification (On the Basis of Pharmacological Effect)",
      ]),
    ],
  },
  Botany: {
    "11": [
      ch("The Living World", [
        "Nomenclature (Binomial Nomenclature, International Code of Nomenclature)",
        "Taxonomic Hierarchy (Species/Genus/Family/Order/Class/Phylum or Division)",
      ]),
      ch("Biological Classification", [
        "Classification (Five Kingdom)",
        "Kingdom : Fungi (Ascomycetes)",
        "Kingdom : Fungi (General Characters/Mycorrhiza)",
        "Kingdom : Monera (Characteristics)",
        "Kingdom : Monera (Mycoplasma)",
        "Kingdom: Fungi (Reproduction in Fungi)",
        "Prions (History, Structure, etc.)",
        "Symbiont (Lichens and Mycorrhiza)",
        "Viroids (History, Structure, etc.)",
      ]),
      ch("Plant Kingdom", [
        "Algae (Chlorophyceae)",
        "Algae (Phaeophyceae)",
        "Algae (Rhodophyceae)",
        "Angiosperms (General Characteristics and Importance)",
        "Bryophytes (Introduction, Characteristics)",
        "Bryophytes (Liverworts)",
        "Bryophytes (Mosses)",
        "Gymnosperms (General Characteristics and Importance)",
        "Plant Life Cycles and Alternation of Generations (Haplo - Diplontic Life Cycle)",
        "Pteridophytes (Characteristics and Importance)",
        "Pteridophytes (Classification of Pteridophytes)",
      ]),
      ch("Morphology of Flowering Plants", [
        "Description of Some Important Families (Brassicaceae)",
        "Description of Some Important Families (Poaceae)",
        "Description of Some Important Families (Solanaceae)",
        "Semi -Technical Description of a Typical Flowering Plant (Floral Formula)",
        "The Flower (Symmetry)",
        "The Flower (Terminology/Symmetry/Thalamus/Position of Floral Parts)",
        "The Flower : Parts of a Flower (Aestivation)",
        "The Flower : Parts of a Flower (Androecium (Stamens))",
        "The Flower : Parts of a Flower (Gynoecium (Carpels))",
        "The Flower : Parts of a Flower (Placentation)",
        "The Fruit (Types of Fruits)",
        "The Inflorescence (Racemose)",
        "The Inflorescence (Solitary Flowers)",
        "The Leaf (Modifications)",
        "The Leaf (Phyllotaxy)",
        "The Root (Regions)",
        "The Root (Types)",
        "The Seed (Structure of Monocotyledonous Seed)",
      ]),
      ch("Anatomy of Flowering Plants", [
        "Anatomy of Dicotyledonous and Monocotyledonous Plants (Anatomy of Monocotyledonous (Isobilateral) Leaf)",
        "Anatomy of Dicotyledonous and Monocotyledonous Plants (Anatomy of Monocotyledonous Root)",
        "Anatomy of Dicotyledonous and Monocotyledonous Plants (Anatomy of Monocotyledonous Stem)",
        "Permanent Tissues (Complex Tissues)",
        "Permanent Tissues (Simple Tissue)",
        "Secondary Growth (Stem) (Cork Cambium)",
        "Secondary Growth (Stem) (Secondary Growth in Dicot Stem)",
        "Secondary Growth (Stem) (Vascular Cambium)",
        "The Tissue System (Epidermal Tissue System)",
        "The Tissue System (Vascular Tissue System)",
      ]),
      ch("Cell: The Unit of Life", [
        "Cell Theory (Formulation of Cell Theory)",
        "Eukaryotic Cells (Cell Membrane)",
        "Eukaryotic Cells (Cell Organelles)",
        "Eukaryotic Cells (Chromosomes)",
        "Eukaryotic Cells (Endomembrane System)",
        "Eukaryotic Cells (Endoplasmic Reticulum)",
        "Eukaryotic Cells (Golgi body)",
        "Eukaryotic Cells (Mitochondria)",
        "Eukaryotic Cells (Nucleolus)",
        "Eukaryotic Cells (Nucleus, Karyotype, etc.)",
        "Eukaryotic Cells (Plastids)",
        "Eukaryotic Cells (Ribosomes)",
        "Prokaryotic Cells (Prokaryotic Ribosomes, Inclusion Bodies, etc.)",
        "What is a Cell ? Overview of the Cell",
      ]),
      ch("Cell Cycle and Cell Division", [
        "Interphase (G1 Phase)",
        "Interphase (G2 Phase)",
        "Interphase (S Phase)",
        "M Phase (Mitosis)",
        "Meiosis (Meiosis I)",
        "Meiosis (Meiosis II)",
        "Phases of the Cell Cycle (Interphase)",
      ]),
      ch("Transport in Plants", [
        "How do Plants Absorb Water? (Apoplast and Symplast Pathway)",
        "Means of Transport (Active Transport)",
        "Phloem Transport (The Pressure Flow or Mass Flow Hypothesis/Girdling Experiment)",
        "Plant-Water Relations (Imbibition)",
        "Plant-Water Relations (Water Potential)",
        "Transpiration (Guttation)",
        "Transpiration (Transpiration and Photosynthesis - A Comparison)",
      ]),
      ch("Mineral Nutrition", [
        "Metabolism of Nitrogen (Biological Nitrogen Fixation)",
        "Metabolism of Nitrogen (Nodule Formation)",
        "Mineral Elements (Essential Mineral Elements)",
      ]),
      ch("Photosynthesis in Higher Plants", [
        "How Many Types of Pigments are Involved in Photosynthesis? (Chlorophyll 'a', Chlorophyll 'b' and c', etc.)",
        "Introduction",
        "Photorespiration",
        "The C4 Pathway (Hatch and Slack Pathway)",
        "The C4 Pathway (Kranz Anatomy, Importance and CAM Cycle)",
        "The Electron Transport (Chemiosmotic Hypothesis)",
        "What is Light Reaction?",
        "Where are ATP and NADPH Used? (Calvin Cycle or C3 Cycle/Primary Acceptor of CO₂/Stages)",
      ]),
      ch("Respiration in Plants", [
        "Aerobic Respiration (Electron Transport Chain)",
        "Aerobic Respiration (TCA Cycle)",
        "Fermentation (Alcoholic and Lactic Acid Fermentation)",
        "Glycolysis (Formation of Pyruvic Acid)",
        "Glycolysis (Steps in Glycolysis- Preparatory Phase)",
        "Respiratory Quotient",
      ]),
      ch("Plant Growth and Development", [
        "Development (Plasticity)",
        "Differentiation, Dedifferentiation and Redifferentiation",
        "Growth (Arithmetic Growth)",
        "Growth (Phases of Growth)",
        "Growth (Phases of Growth-Phases of Cell Elongation)",
        "Introduction",
        "Photoperiodism (Introduction and Importance of Photoperiodism)",
        "Physiological Effects of Plant Growth Regulators (Abscisic Acid)",
        "Physiological Effects of Plant Growth Regulators (Auxins)",
        "Physiological Effects of Plant Growth Regulators (Ethylene)",
        "Physiological Effects of Plant Growth Regulators (Gibberellins)",
        "Plant Growth Regulators (Effects of PGR)",
      ]),
    ],
    "12": [
      ch("Sexual Reproduction in Flowering Plants", [
        "Double Fertilisation",
        "Fertilisation",
        "Pollination (Types of Pollination/Agents of Pollination/Outbreeding Devices)",
        "Post-Fertilisation : Structures and Events (Endosperm)",
        "Seed (Formation of Seed, Classification of Seed)",
        "Structure and Development of Anther and Male Gametophyte",
        "Structure and Development of Anther and Male Gametophyte (Microsporogenesis, T.S. of Anther, etc.)",
        "Structure and Development of Ovule and Female Gametophyte",
        "The Fruit (Types of Fruits on the Basis of Development, Epicarp, Mesocarp and Endocarp)",
      ]),
      ch("Principles of Inheritance and Variation", [
        "Exceptions to Mendelian Principles (Co-Dominance)",
        "Exceptions to Mendelian Principles (Incomplete Dominance)",
        "Genetic Disorders (Pedigree Analysis)",
        "Genetic Disorders: Chromosomal Disorders (Down's Syndrome)",
        "Genetic Disorders: Chromosomal Disorders (Klinefelter's Syndrome)",
        "Genetic Disorders: Mendelian Disorders (Autosomal Recessive, Autosomal Dominant Disorders)",
        "Genetic Disorders: Mendelian Disorders (Color Blindness)",
        "Genetic Disorders: Mendelian Disorders (Haemophilia)",
        "Genetic Disorders: Mendelian Disorders (Sickle-cell Anaemia)",
        "Inheritance of One Gene (Concept of Factors, Law of Dominance, etc.)",
        "Inheritance of One Gene (Law of Dominance)",
        "Inheritance of One Gene (Monohybrid Cross)",
        "Inheritance of One Gene (Punnett Square)",
        "Inheritance of One Gene (Test Cross)",
        "Inheritance of Two Gene (Dihybrid Cross)",
        "Inheritance of Two Gene (Dihybrid Cross, Law of Independent Assortment, etc.)",
        "Mendel's Laws of Inheritance (Selection of Pea Plant)",
        "Polygenic Inheritance and Pleiotropy (Pleiotropy)",
        "Polygenic Inheritance and Pleiotropy (Polygenic Inheritance)",
        "Sex Determination (Sex Determination in Honey Bee)",
        "Sex Determination in Other Organisms (Honey bee, Birds, etc.)",
        "Two Genes Interaction (w.r.t Post-Mendelism) (Chromosomal Theory of Inheritance and its Verification)",
        "Two Genes Interaction (w.r.t Post-Mendelism) (Linkage and Recombination, Recombination Map, etc.)",
      ]),
      ch("Molecular Basis of Inheritance", [
        "DNA Fingerprinting",
        "DNA Replication (The Machinery and Enzymes for DNA Replication, Mechanism)",
        "Genetic Code (Genetic Code/tRNA -The Adapter Molecule)",
        "Genetic Code (Mutations and the Genetic Code)",
        "Genetic Code (Salient Features of Genetic Code)",
        "Human Genome Project (Methodologies/Salient Features of Human Genome)",
        "Packaging of the DNA Helix (Nucleosome, Histone Proteins etc.)",
        "Regulation of Gene Expression (Lac-Operon)",
        "Replication (The Experimental Proof)",
        "RNA World",
        "The DNA (Chargaff's Rule)",
        "The DNA (Derivation of DNA Structure and Central Dogma)",
        "The DNA (Nitrogen Base)",
        "The DNA (Nucleotide)",
        "The Search For Genetic Material (Hershey-Chase Experiment)",
        "The Search For Genetic Material (Properties of Genetic Material (DNA Versus RNA))",
        "Transcription (Initiation, Elongation and Termination Process, etc.)",
        "Transcription (Post Transcriptional Process)",
        "Transcription (Process of Transcription)",
        "Transcription (RNA Polymerases)",
        "Transcription (Transcription Unit)",
        "Transcription (Types of RNA)",
        "Translation (Process of Translation)",
        "Transposons",
      ]),
      ch("Strategies for Enhancement in Food Production", [
        "Introduction",
        "Plant Breeding for Disease Resistance (Methods of Breeding for Disease Resistance, Mutation)",
      ]),
      ch("Microbes in Human Welfare", [
        "Microbes as Biofertilizers",
        "Microbes in Household Products",
        "Microbes in Industrial Products (Bioactive Molecules)",
        "Microbes in Industrial Products (Chemicals)",
        "Microbes in Industrial Products (Enzymes)",
        "Microbes in Industrial Products (Fermented Beverages)",
        "Microbes in Sewage Treatment (Primary Treatment)",
      ]),
      ch("Organisms and Populations", [
        "Organism and its Environment (Adaptations)",
        "Population Growth (Natality, Mortality, etc.)",
        "Population Growth Curve (J - Shaped and S - Shaped)",
        "Population Interactions (Types of Population Interactions)",
        "Populations (Growth Models : Exponential and Logistic Growth)",
        "Populations (Population Attributes)",
      ]),
      ch("Ecosystem", [
        "Decomposition (Process Involved in Decomposition)",
        "Ecological Pyramids (Pyramid of Biomass)",
        "Ecological Pyramids (Pyramid of Energy)",
        "Ecological Succession (Types of Successional Communities)",
        "Energy Flow (Food Chain)",
        "Introduction",
        "Productivity (GPP)",
        "Productivity (NPP)",
        "Productivity (Primary Productivity)",
      ]),
      ch("Biodiversity and Conservation", [
        "Biodiversity (Introduction)",
        "Biodiversity (Patterns of Biodiversity)",
        "Biodiversity Conservation (Narrowly Utilitarian)",
        "Biological Diversity Act 2002 (Earth Summit, CBD, etc.)",
        "Ex-Situ Conservation (Botanical Gardens, Zoological Parks, etc.)",
        "Importance of Species Diversity to the Ecosystem (Productivity Stability Hypothesis, Rivet Popper Hypothesis)",
        "In-situ Conservation (Hot Spots, Major Hotspots in India, etc.)",
        "Latitudinal Gradients (Species-Area Relationships)",
        "Loss of Biodiversity (IUCN Red List, the Evil Quartet, etc.)",
        "Pattern of Biodiversity (Latitudinal Gradients)",
      ]),
      ch("Environmental Issues", [
        "Air Pollution (Control of Air Pollution)",
        "Ozone (Ozone Depletion in the Stratosphere)",
        "Water Pollution and its Control (Domestic Sewage and Industrial Effluents)",
      ]),
    ],
  },
  Zoology: {
    "11": [
      ch("Animal Kingdom", [
        "Basis of Classification (Notochord)",
        "Basis of Classification (Symmetry)",
        "Broad Classification of Kingdom Animalia (Coelom)",
        "Chordata - Vertebrata (Pisces (Chondrichthyes and Osteichthyes))",
        "Chordata - Vertebrata (Tetrapoda - (Amphibia, Reptilia))",
        "Chordata and Non Chordata (Differences or Common Examples)",
        "Classification of Animals (Non Chordata) (Characteristic Feature and Examples - Annelida)",
        "Classification of Animals (Non Chordata) (Characteristic Feature and Examples - Arthropoda)",
        "Classification of Animals (Non Chordata) (Characteristic Feature and Examples - Aschelminthes)",
        "Classification of Animals (Non Chordata) (Characteristic Feature and Examples - Coelenterata/Cnidaria)",
        "Classification of Animals (Non Chordata) (Characteristic Feature and Examples - Ctenophora)",
        "Classification of Animals (Non Chordata) (Characteristic Feature and Examples - Echinodermata)",
        "Classification of Animals (Non Chordata) (Characteristic Feature and Examples - Hemichordata)",
        "Classification of Animals (Non Chordata) (Characteristic Feature and Examples - Mollusca)",
        "Classification of Animals (Non Chordata) (Characteristic Feature and Examples - Platyhelminthes)",
        "Classification of Animals (Non Chordata) (Characteristic Feature and Examples - Porifera)",
        "Classification of Chordata (Characteristic Feature and Examples - Class Aves)",
        "Classification of Chordata (Characteristic Feature and Examples - Class Mammalia)",
        "Classification of Chordata - Pisces (Class - Chondrichthyes)",
        "Classification of Chordata - Pisces (Class - Osteichthyes)",
        "Classification of Chordata - Protochordata (Cephalochordata)",
        "Classification of Chordata - Vertebrata (Class - Cyclostomata)",
        "Introduction (General Description of Animal Kingdom)",
        "Phylum Chordata (Basic Features of Chordates)",
      ]),
      ch("Structural Organisation in Animals (Animal Tissues)", [
        "Cockroach (External Morphology)",
        "Cockroach - Anatomy (Digestive System)",
        "Cockroach - Anatomy (Excretory System)",
        "Cockroach - Anatomy (Nervous System)",
        "Cockroach - Anatomy (Reproductive System (Male and Female))",
        "Cockroach - Anatomy (Sensory Organs)",
        "Connective Tissue (Loose Connective Tissue)",
        "Connective Tissue (Specialised Connective Tissue)",
        "Connective Tissue - Specialised Connective Tissue (Blood)",
        "Dense Connective Tissue (Irregular Dense Connective Tissue)",
        "Dense Connective Tissue (Regular Dense Connective Tissue)",
        "Earthworm (Habits and Morphology)",
        "Earthworm - Anatomy (Sensory system)",
        "Epithelial Tissue (Cell-cell communication junctions)",
        "Epithelial Tissue (Compound Epithelium)",
        "Epithelial Tissue (Glandular Epithelium)",
        "Epithelial Tissue (Simple Epithelium)",
        "Frog (External Morphology)",
        "Frog - Anatomy (Blood Vascular System)",
        "Frog - Anatomy (Habits and Morphology)",
        "Frog - Anatomy (Nervous System)",
        "Frog - Anatomy (Respiratory System)",
      ], ["Structural Organisation in Animals"]),
      ch("Biomolecules", [
        "Amino Acids (Different Types of Amino Acid)",
        "Analysis of Chemical Composition (DNA)",
        "Analysis of Chemical Composition (Elemental Analysis)",
        "Carbohydrates (Composition of Cell Wall)",
        "Carbohydrates (Disaccharides)",
        "Carbohydrates (Polysaccharides)",
        "Enzymes (Classification and Nomenclature of Enzymes)",
        "Enzymes (Co-factors)",
        "Enzymes (Competitive, Non Competitive, etc.)",
        "Enzymes (Inhibition of Enzyme Action)",
        "Enzymes (Introduction)",
        "Enzymes (Mechanism of Enzyme Action)",
        "Lipids (Glycerol and Fatty Acid)",
        "Lipids (Phospholipid, Triglycerides, etc.)",
        "Nature of Bond Linking Monomers in Polymer (Glycosidic, Phosphodiester, etc.)",
        "Nature of Bond Linking Monomers in Polymer (Peptide Bond)",
        "Nucleic Acids (DNA)",
        "Primary and Secondary Metabolites (Examples and Function)",
        "Proteins (Amino Acids)",
        "Proteins (Function of Protein)",
        "Proteins (Structure of Proteins)",
      ]),
      ch("Digestion and Absorption", [
        "Alimentary Canal (Structure and Functions of Alimentary Canal, Histology)",
        "Digestion of Food",
        "Digestion of Food (Role of Pancreatic Juice, Succus Entericus, etc.)",
        "Digestive Gland (Gastric Glands and Intestinal Glands)",
        "Digestive Gland (Pancreas)",
        "Digestive Gland (Salivary Gland)",
        "Digestive System (Introduction, Food and its Component, etc.)",
      ]),
      ch("Breathing and Exchange of Gases", [
        "Disorders of Respiratory System",
        "Exchange of Gases (O₂ and CO₂) (Atm pO₂ and pCO₂, Alveoli, etc.)",
        "Human Respiratory System",
        "Mechanism of Breathing (Inspiration and its Associated Muscle)",
        "Respiratory Capacities (Vital Capacity)",
        "Respiratory Organs (Gills, Trachea, etc.)",
        "Respiratory Volume (Expiratory Reserve Volume)",
        "Respiratory Volumes and Capacities (TV, IRV, etc.)",
        "Transport of Gases (O₂ and CO₂) (Transport of Oxygen)",
      ]),
      ch("Body Fluids and Circulation", [
        "Blood (Plasma)",
        "Blood - Formed Element (Leucocytes and Disorder)",
        "Blood Groups (Abo Blood Groups)",
        "Blood Groups (Rh Grouping)",
        "Cardiac cycle",
        "Circulatory Pathways",
        "Coagulation of Blood",
        "ECG (Role of PQRST and Clinical Significance)",
        "Human Circulatory System (Heart)",
        "Regulation of Cardiac Activity (Effect of Medullary Hormones on Heart)",
      ]),
      ch("Excretory Products and their Elimination", [
        "Disorders of the Excretory System",
        "Functions of the Tubules (PCT)",
        "Functions of the Tubules (PCT, Henle's Loop, etc.)",
        "Human Excretory System",
        "Introduction and Excretory Products (Osmoregulation in Different Organisms)",
        "Mechanism of Concentration of the Filtrate (Counter Current Mechanism)",
        "Regulation of Kidney Function (ADH, RAAS, etc.)",
        "Regulation of Kidney Function - Heart (ANF)",
        "Regulation of Kidney Function - Kidney (JGA, RAAS System)",
      ]),
      ch("Locomotion and Movement", [
        "Disorder of Muscular and Skeletal System",
        "Joints (Fibrous, Cartilaginous, etc.)",
        "Mechanism of Muscle Contraction (Sliding Filament Theory of Muscle Contraction)",
        "Skeletal System (Appendicular Skeleton)",
        "Skeletal System (Axial skeleton)",
        "Types of Movement (Flagellar Movements)",
        "Types of Muscle (Cardiac Muscle)",
        "Types of Muscle (Smooth Muscle)",
      ]),
      ch("Neural Control and Coordination", [
        "Conduction of Nerve Impulse (Saltatory Conduction)",
        "Meninges (Types and Function)",
        "Parts of Brain (Forebrain)",
        "Parts of Brain (Hindbrain)",
        "Sensory Reception and Processing - Ear (Anatomy of Ear)",
        "Sensory Reception and Processing - Eye (Parts of Eye)",
      ]),
      ch("Chemical Coordination and Integration", [
        "Adrenal Gland (Adrenal Cortex and its Hormones)",
        "Adrenal Gland (Adrenal Medulla and its Hormones)",
        "Classification of Hormone (Protein Hormone and Steroid Hormone)",
        "Hormonal Disorders (Examples)",
        "Hormones (Current and Scientific Definition of Hormones)",
        "Hormones of Gastrointestinal Tract (GI Tract Hormone and its Function)",
        "Human Endocrine System (Location of Endocrine Glands and Organs in Human Body)",
        "Hypothalamus (Location of Hypothalamus, Hypothalamic Hormone)",
        "Ovary (Hormones and Function)",
        "Pancreas (Insulin and Glucagon)",
        "Parathyroid (Hormones and Function)",
        "Pituitary Gland (Anterior and Posterior Pituitary)",
        "Thyroid (Hormones and Function)",
      ]),
    ],
    "12": [
      ch("Human Reproduction", [
        "Cleavage (Types of Cleavage)",
        "Embryonic Development (Embryonic Development of Organs in Foetus at Various Stages)",
        "Embryonic Development (Morula, Blastula, etc.)",
        "Fertilisation (Capacitation, Fast Block to Polyspermy, etc.)",
        "Fertilisation (Mechanism of Fertilisation, Significance of Fertilisation)",
        "Gametogenesis (Hormonal Control of Spermatogenesis)",
        "Gametogenesis (Oogenesis)",
        "Gametogenesis (Spermatogenesis and Oogenesis)",
        "Gametogenesis (Spermatogenesis)",
        "Gametogenesis (Structure of Sperm)",
        "Lactation",
        "Lactation (Definition, Colostrum)",
        "Menstrual Cycle (Menarche, Various Events During Menstrual Cycle, etc.)",
        "Parturition (Foetal Ejection Reflex, Dilation and Expulsion Stage)",
        "Placenta (Placenta Hormones)",
        "Pregnancy/Gestation (Gestation Period/Trimesters)",
        "The Female Reproductive System (External Genitalia)",
        "The Female Reproductive System (Part of Female Reproductive System with Accessory Glands)",
        "The Male Reproductive System (Part of Male Reproductive System with Accessory Glands)",
      ]),
      ch("Reproductive Health", [
        "Assisted Reproductive Technologies (ART, IVF, etc.)",
        "Birth Control (Barrier Methods)",
        "Birth Control (IUDS)",
        "Birth Control (Natural Methods)",
        "Birth Control (Oral Contraceptive)",
        "Birth Control (Sterilisation Procedure)",
        "Reproductive Health - Problems and Strategies (Family Planning Programme, RCH Programmes, etc.)",
        "Sexually Transmitted Diseases (STDs)",
      ]),
      ch("Human Health and Disease", [
        "AIDS (Acquired Immuno Deficiency Syndrome) (HIV Virus, Modes of Transmission, etc.)",
        "Cancer (Introduction)",
        "Common Diseases in Humans (Disease Causing Organism)",
        "Common Diseases in Humans (Life Cycle of Plasmodium)",
        "Common Diseases in Humans (Typhoid, Pneumonia, etc.)",
        "Drugs (Different Types of Drugs)",
        "Drugs (Opioids, Heroin, etc.)",
        "Drugs and Alcohol Abuse (Effects of Drug/Alcohol Abuse)",
        "Immunity (Acquired Immunity)",
        "Immunity (Active and Passive Immunity)",
        "Immunity (Innate Immunity)",
        "Immunity (Structure of Antibody)",
        "Lymphoid Organs (Secondary Lymphoid Organs)",
        "Miscellaneous",
      ]),
      ch("Biotechnology - Principles and Processes", [
        "Cloning Vectors (pBR322, Cosmids, etc.)",
        "Cloning Vectors (Plasmid (pBR322))",
        "Cloning Vectors (Vectors for Plants and Animals (Ti Plasmid, Retrovirus))",
        "Gel Electrophoresis (Separation and Isolation of DNA Fragments)",
        "Identification of Clones having Recombinant DNA (Antibiotic Resistance Method)",
        "Identification of Clones having Recombinant DNA (Blue White Screening Method (Insertional Inactivation))",
        "Methods of Gene Transfer (Gene Gun, Electroporation, etc.)",
        "Obtaining the Foreign Gene Product (Bioreactors)",
        "Polymerase Chain Reaction (Denaturation, Annealing, etc.)",
        "Principles of Biotechnology (Introduction)",
        "Processes of Recombinant DNA Technologies (Agarose Gel Electrophoresis)",
        "Processes of Recombinant DNA Technologies (Amplification of Gene of Interest Using PCR)",
        "Processes of Recombinant DNA Technologies (Insertion of Recombinant DNA into the Host Cell/Organism)",
        "Processes of Recombinant DNA Technologies (Isolation of the Genetic Material (DNA))",
        "Restriction Enzymes (Endonuclease and Exonuclease, Nomenclature of Restriction Enzymes)",
        "Tools of Recombinant DNA Technology (Restriction Enzymes and Other Enzymes)",
      ], ["Biotechnology: Principles and Processes"]),
      ch("Biotechnology and its Applications", [
        "Biotechnological Applications in Agriculture (Bt Cotton)",
        "Biotechnological Applications in Agriculture (Green Revolution)",
        "Biotechnological Applications in Agriculture (Introduction)",
        "Biotechnological Applications in Agriculture (RNA Interference)",
        "Biotechnological Applications in Medicine (Gene Therapy)",
        "Biotechnological Applications in Medicine (Molecular Diagnosis)",
        "Biotechnological Applications in Medicine (Recombinant Insulin - Humulin)",
        "Biotechnological Applications in Medicine (Treatment of Cancer)",
        "Transgenic Animals (Benefits of Transgenic Animals)",
      ]),
      ch("Evolution", [
        "A Brief Account of Evolution (Evolution of Animal Forms through Geological Periods)",
        "Adaptive Radiation (Convergence and Divergence)",
        "Adaptive Radiation (Darwin’s Finches, Australian Marsupials, etc.)",
        "Convergent and Divergent Evolution",
        "Evidences for Evolution (Anatomical and Morphological Evidences)",
        "Evidences for Evolution (Biogeographical Evidences)",
        "Evidences for Evolution (Embryological Evidences)",
        "Evidences for Evolution (Morphological Evidences : Homologous Structures, Analogous Structures)",
        "Evidences for Evolution (Palaeontological Evidences)",
        "Hardy-Weinberg Principle (Factors Affecting Hardy-Weinberg Principle)",
        "Hardy-Weinberg Principle (Introduction)",
        "Mechanism of Evolution (Variation, Mutation and Recombination)",
        "Natural Selection (Types of Natural Selection)",
        "Oparin-Haldane Theory (Theory)",
        "Origin and Evolution of Man (Prehistoric Species, Prosimian Ancestors, etc.)",
      ]),
    ],
  },
};
