/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as JoinInternRouteImport } from './routes/join-intern'
import { Route as JoinMentorRouteImport } from './routes/join-mentor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MySessionsRouteImport } from './routes/my-sessions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AdminAuthRouteImport } from './routes/admin.auth'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as InternAuthRouteImport } from './routes/intern/auth'
import { Route as InternCertificateRouteImport } from './routes/intern/certificate'
import { Route as InternDashboardRouteImport } from './routes/intern/dashboard'
import { Route as InternOfferLetterRouteImport } from './routes/intern/offer-letter'
import { Route as InternProfileRouteImport } from './routes/intern/profile'
import { Route as LectureSessionIdRouteImport } from './routes/lecture.$sessionId'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalRefundRouteImport } from './routes/legal/refund'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as MentorOnboardingApplicationIdRouteImport } from './routes/mentor-onboarding/$applicationId'
import { Route as MentorProfileMentorIdRouteImport } from './routes/mentor-profile.$mentorId'
import { Route as MentorSessionOfferingIdRouteImport } from './routes/mentor-session/$offeringId'
import { Route as MentorDashboardRouteImport } from './routes/mentor.dashboard'
import { Route as PromoterAuthRouteImport } from './routes/promoter.auth'
import { Route as PromoterDashboardRouteImport } from './routes/promoter.dashboard'
import { Route as SimulatorLiveRouteImport } from './routes/simulator/live'
import { Route as SoldTestIdRouteImport } from './routes/sold-test.$id'
import { Route as TestAnalysisTestIdRouteImport } from './routes/test-analysis.$testId'
import { Route as TestResultAttemptIdRouteImport } from './routes/test-result.$attemptId'
import { Route as TestTestIdRouteImport } from './routes/test.$testId'
import { Route as VerifyCertificateIdRouteImport } from './routes/verify.$certificateId'
import { Route as CourseKindIdRouteImport } from './routes/course.$kind.$id'
import { Route as InternTrialCodeRouteImport } from './routes/intern/trial.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinInternRoute = JoinInternRouteImport.update({
  id: '/join-intern',
  path: '/join-intern',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinMentorRoute = JoinMentorRouteImport.update({
  id: '/join-mentor',
  path: '/join-mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MySessionsRoute = MySessionsRouteImport.update({
  id: '/my-sessions',
  path: '/my-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/auth',
  path: '/admin/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InternAuthRoute = InternAuthRouteImport.update({
  id: '/intern/auth',
  path: '/intern/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InternCertificateRoute = InternCertificateRouteImport.update({
  id: '/intern/certificate',
  path: '/intern/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const InternDashboardRoute = InternDashboardRouteImport.update({
  id: '/intern/dashboard',
  path: '/intern/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InternOfferLetterRoute = InternOfferLetterRouteImport.update({
  id: '/intern/offer-letter',
  path: '/intern/offer-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const InternProfileRoute = InternProfileRouteImport.update({
  id: '/intern/profile',
  path: '/intern/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LectureSessionIdRoute = LectureSessionIdRouteImport.update({
  id: '/lecture/$sessionId',
  path: '/lecture/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorOnboardingApplicationIdRoute =
  MentorOnboardingApplicationIdRouteImport.update({
    id: '/mentor-onboarding/$applicationId',
    path: '/mentor-onboarding/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentorProfileMentorIdRoute = MentorProfileMentorIdRouteImport.update({
  id: '/mentor-profile/$mentorId',
  path: '/mentor-profile/$mentorId',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorSessionOfferingIdRoute = MentorSessionOfferingIdRouteImport.update({
  id: '/mentor-session/$offeringId',
  path: '/mentor-session/$offeringId',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorDashboardRoute = MentorDashboardRouteImport.update({
  id: '/mentor/dashboard',
  path: '/mentor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoterAuthRoute = PromoterAuthRouteImport.update({
  id: '/promoter/auth',
  path: '/promoter/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoterDashboardRoute = PromoterDashboardRouteImport.update({
  id: '/promoter/dashboard',
  path: '/promoter/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorLiveRoute = SimulatorLiveRouteImport.update({
  id: '/simulator/live',
  path: '/simulator/live',
  getParentRoute: () => rootRouteImport,
} as any)
const SoldTestIdRoute = SoldTestIdRouteImport.update({
  id: '/sold-test/$id',
  path: '/sold-test/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TestAnalysisTestIdRoute = TestAnalysisTestIdRouteImport.update({
  id: '/test-analysis/$testId',
  path: '/test-analysis/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestResultAttemptIdRoute = TestResultAttemptIdRouteImport.update({
  id: '/test-result/$attemptId',
  path: '/test-result/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTestIdRoute = TestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertificateIdRoute = VerifyCertificateIdRouteImport.update({
  id: '/$certificateId',
  path: '/$certificateId',
  getParentRoute: () => VerifyRoute,
} as any)
const CourseKindIdRoute = CourseKindIdRouteImport.update({
  id: '/course/$kind/$id',
  path: '/course/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InternTrialCodeRoute = InternTrialCodeRouteImport.update({
  id: '/intern/trial/$code',
  path: '/intern/trial/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/join-intern': typeof JoinInternRoute
  '/join-mentor': typeof JoinMentorRoute
  '/login': typeof LoginRoute
  '/my-sessions': typeof MySessionsRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tickets': typeof TicketsRoute
  '/verify': typeof VerifyRouteWithChildren
  '/admin/auth': typeof AdminAuthRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/intern/auth': typeof InternAuthRoute
  '/intern/certificate': typeof InternCertificateRoute
  '/intern/dashboard': typeof InternDashboardRoute
  '/intern/offer-letter': typeof InternOfferLetterRoute
  '/intern/profile': typeof InternProfileRoute
  '/lecture/$sessionId': typeof LectureSessionIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/mentor-onboarding/$applicationId': typeof MentorOnboardingApplicationIdRoute
  '/mentor-profile/$mentorId': typeof MentorProfileMentorIdRoute
  '/mentor-session/$offeringId': typeof MentorSessionOfferingIdRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/promoter/auth': typeof PromoterAuthRoute
  '/promoter/dashboard': typeof PromoterDashboardRoute
  '/simulator/live': typeof SimulatorLiveRoute
  '/sold-test/$id': typeof SoldTestIdRoute
  '/test-analysis/$testId': typeof TestAnalysisTestIdRoute
  '/test-result/$attemptId': typeof TestResultAttemptIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/course/$kind/$id': typeof CourseKindIdRoute
  '/intern/trial/$code': typeof InternTrialCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/join-intern': typeof JoinInternRoute
  '/join-mentor': typeof JoinMentorRoute
  '/login': typeof LoginRoute
  '/my-sessions': typeof MySessionsRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tickets': typeof TicketsRoute
  '/verify': typeof VerifyRouteWithChildren
  '/admin/auth': typeof AdminAuthRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/intern/auth': typeof InternAuthRoute
  '/intern/certificate': typeof InternCertificateRoute
  '/intern/dashboard': typeof InternDashboardRoute
  '/intern/offer-letter': typeof InternOfferLetterRoute
  '/intern/profile': typeof InternProfileRoute
  '/lecture/$sessionId': typeof LectureSessionIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/mentor-onboarding/$applicationId': typeof MentorOnboardingApplicationIdRoute
  '/mentor-profile/$mentorId': typeof MentorProfileMentorIdRoute
  '/mentor-session/$offeringId': typeof MentorSessionOfferingIdRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/promoter/auth': typeof PromoterAuthRoute
  '/promoter/dashboard': typeof PromoterDashboardRoute
  '/simulator/live': typeof SimulatorLiveRoute
  '/sold-test/$id': typeof SoldTestIdRoute
  '/test-analysis/$testId': typeof TestAnalysisTestIdRoute
  '/test-result/$attemptId': typeof TestResultAttemptIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/course/$kind/$id': typeof CourseKindIdRoute
  '/intern/trial/$code': typeof InternTrialCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/join-intern': typeof JoinInternRoute
  '/join-mentor': typeof JoinMentorRoute
  '/login': typeof LoginRoute
  '/my-sessions': typeof MySessionsRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tickets': typeof TicketsRoute
  '/verify': typeof VerifyRouteWithChildren
  '/admin/auth': typeof AdminAuthRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/intern/auth': typeof InternAuthRoute
  '/intern/certificate': typeof InternCertificateRoute
  '/intern/dashboard': typeof InternDashboardRoute
  '/intern/offer-letter': typeof InternOfferLetterRoute
  '/intern/profile': typeof InternProfileRoute
  '/lecture/$sessionId': typeof LectureSessionIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/mentor-onboarding/$applicationId': typeof MentorOnboardingApplicationIdRoute
  '/mentor-profile/$mentorId': typeof MentorProfileMentorIdRoute
  '/mentor-session/$offeringId': typeof MentorSessionOfferingIdRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/promoter/auth': typeof PromoterAuthRoute
  '/promoter/dashboard': typeof PromoterDashboardRoute
  '/simulator/live': typeof SimulatorLiveRoute
  '/sold-test/$id': typeof SoldTestIdRoute
  '/test-analysis/$testId': typeof TestAnalysisTestIdRoute
  '/test-result/$attemptId': typeof TestResultAttemptIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/verify/$certificateId': typeof VerifyCertificateIdRoute
  '/course/$kind/$id': typeof CourseKindIdRoute
  '/intern/trial/$code': typeof InternTrialCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/help'
    | '/join-intern'
    | '/join-mentor'
    | '/login'
    | '/my-sessions'
    | '/profile'
    | '/purchases'
    | '/sitemap.xml'
    | '/tickets'
    | '/verify'
    | '/admin/auth'
    | '/admin/dashboard'
    | '/intern/auth'
    | '/intern/certificate'
    | '/intern/dashboard'
    | '/intern/offer-letter'
    | '/intern/profile'
    | '/lecture/$sessionId'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/mentor-onboarding/$applicationId'
    | '/mentor-profile/$mentorId'
    | '/mentor-session/$offeringId'
    | '/mentor/dashboard'
    | '/promoter/auth'
    | '/promoter/dashboard'
    | '/simulator/live'
    | '/sold-test/$id'
    | '/test-analysis/$testId'
    | '/test-result/$attemptId'
    | '/test/$testId'
    | '/verify/$certificateId'
    | '/course/$kind/$id'
    | '/intern/trial/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/help'
    | '/join-intern'
    | '/join-mentor'
    | '/login'
    | '/my-sessions'
    | '/profile'
    | '/purchases'
    | '/sitemap.xml'
    | '/tickets'
    | '/verify'
    | '/admin/auth'
    | '/admin/dashboard'
    | '/intern/auth'
    | '/intern/certificate'
    | '/intern/dashboard'
    | '/intern/offer-letter'
    | '/intern/profile'
    | '/lecture/$sessionId'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/mentor-onboarding/$applicationId'
    | '/mentor-profile/$mentorId'
    | '/mentor-session/$offeringId'
    | '/mentor/dashboard'
    | '/promoter/auth'
    | '/promoter/dashboard'
    | '/simulator/live'
    | '/sold-test/$id'
    | '/test-analysis/$testId'
    | '/test-result/$attemptId'
    | '/test/$testId'
    | '/verify/$certificateId'
    | '/course/$kind/$id'
    | '/intern/trial/$code'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/help'
    | '/join-intern'
    | '/join-mentor'
    | '/login'
    | '/my-sessions'
    | '/profile'
    | '/purchases'
    | '/sitemap.xml'
    | '/tickets'
    | '/verify'
    | '/admin/auth'
    | '/admin/dashboard'
    | '/intern/auth'
    | '/intern/certificate'
    | '/intern/dashboard'
    | '/intern/offer-letter'
    | '/intern/profile'
    | '/lecture/$sessionId'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/mentor-onboarding/$applicationId'
    | '/mentor-profile/$mentorId'
    | '/mentor-session/$offeringId'
    | '/mentor/dashboard'
    | '/promoter/auth'
    | '/promoter/dashboard'
    | '/simulator/live'
    | '/sold-test/$id'
    | '/test-analysis/$testId'
    | '/test-result/$attemptId'
    | '/test/$testId'
    | '/verify/$certificateId'
    | '/course/$kind/$id'
    | '/intern/trial/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  JoinInternRoute: typeof JoinInternRoute
  JoinMentorRoute: typeof JoinMentorRoute
  LoginRoute: typeof LoginRoute
  MySessionsRoute: typeof MySessionsRoute
  ProfileRoute: typeof ProfileRoute
  PurchasesRoute: typeof PurchasesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TicketsRoute: typeof TicketsRoute
  VerifyRoute: typeof VerifyRouteWithChildren
  AdminAuthRoute: typeof AdminAuthRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  InternAuthRoute: typeof InternAuthRoute
  InternCertificateRoute: typeof InternCertificateRoute
  InternDashboardRoute: typeof InternDashboardRoute
  InternOfferLetterRoute: typeof InternOfferLetterRoute
  InternProfileRoute: typeof InternProfileRoute
  LectureSessionIdRoute: typeof LectureSessionIdRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalTermsRoute: typeof LegalTermsRoute
  MentorOnboardingApplicationIdRoute: typeof MentorOnboardingApplicationIdRoute
  MentorProfileMentorIdRoute: typeof MentorProfileMentorIdRoute
  MentorSessionOfferingIdRoute: typeof MentorSessionOfferingIdRoute
  MentorDashboardRoute: typeof MentorDashboardRoute
  PromoterAuthRoute: typeof PromoterAuthRoute
  PromoterDashboardRoute: typeof PromoterDashboardRoute
  SimulatorLiveRoute: typeof SimulatorLiveRoute
  SoldTestIdRoute: typeof SoldTestIdRoute
  TestAnalysisTestIdRoute: typeof TestAnalysisTestIdRoute
  TestResultAttemptIdRoute: typeof TestResultAttemptIdRoute
  TestTestIdRoute: typeof TestTestIdRoute
  CourseKindIdRoute: typeof CourseKindIdRoute
  InternTrialCodeRoute: typeof InternTrialCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-intern': {
      id: '/join-intern'
      path: '/join-intern'
      fullPath: '/join-intern'
      preLoaderRoute: typeof JoinInternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-mentor': {
      id: '/join-mentor'
      path: '/join-mentor'
      fullPath: '/join-mentor'
      preLoaderRoute: typeof JoinMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-sessions': {
      id: '/my-sessions'
      path: '/my-sessions'
      fullPath: '/my-sessions'
      preLoaderRoute: typeof MySessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auth': {
      id: '/admin/auth'
      path: '/admin/auth'
      fullPath: '/admin/auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intern/auth': {
      id: '/intern/auth'
      path: '/intern/auth'
      fullPath: '/intern/auth'
      preLoaderRoute: typeof InternAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intern/certificate': {
      id: '/intern/certificate'
      path: '/intern/certificate'
      fullPath: '/intern/certificate'
      preLoaderRoute: typeof InternCertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intern/dashboard': {
      id: '/intern/dashboard'
      path: '/intern/dashboard'
      fullPath: '/intern/dashboard'
      preLoaderRoute: typeof InternDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intern/offer-letter': {
      id: '/intern/offer-letter'
      path: '/intern/offer-letter'
      fullPath: '/intern/offer-letter'
      preLoaderRoute: typeof InternOfferLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intern/profile': {
      id: '/intern/profile'
      path: '/intern/profile'
      fullPath: '/intern/profile'
      preLoaderRoute: typeof InternProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecture/$sessionId': {
      id: '/lecture/$sessionId'
      path: '/lecture/$sessionId'
      fullPath: '/lecture/$sessionId'
      preLoaderRoute: typeof LectureSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-onboarding/$applicationId': {
      id: '/mentor-onboarding/$applicationId'
      path: '/mentor-onboarding/$applicationId'
      fullPath: '/mentor-onboarding/$applicationId'
      preLoaderRoute: typeof MentorOnboardingApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-profile/$mentorId': {
      id: '/mentor-profile/$mentorId'
      path: '/mentor-profile/$mentorId'
      fullPath: '/mentor-profile/$mentorId'
      preLoaderRoute: typeof MentorProfileMentorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-session/$offeringId': {
      id: '/mentor-session/$offeringId'
      path: '/mentor-session/$offeringId'
      fullPath: '/mentor-session/$offeringId'
      preLoaderRoute: typeof MentorSessionOfferingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/dashboard': {
      id: '/mentor/dashboard'
      path: '/mentor/dashboard'
      fullPath: '/mentor/dashboard'
      preLoaderRoute: typeof MentorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promoter/auth': {
      id: '/promoter/auth'
      path: '/promoter/auth'
      fullPath: '/promoter/auth'
      preLoaderRoute: typeof PromoterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promoter/dashboard': {
      id: '/promoter/dashboard'
      path: '/promoter/dashboard'
      fullPath: '/promoter/dashboard'
      preLoaderRoute: typeof PromoterDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator/live': {
      id: '/simulator/live'
      path: '/simulator/live'
      fullPath: '/simulator/live'
      preLoaderRoute: typeof SimulatorLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sold-test/$id': {
      id: '/sold-test/$id'
      path: '/sold-test/$id'
      fullPath: '/sold-test/$id'
      preLoaderRoute: typeof SoldTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-analysis/$testId': {
      id: '/test-analysis/$testId'
      path: '/test-analysis/$testId'
      fullPath: '/test-analysis/$testId'
      preLoaderRoute: typeof TestAnalysisTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-result/$attemptId': {
      id: '/test-result/$attemptId'
      path: '/test-result/$attemptId'
      fullPath: '/test-result/$attemptId'
      preLoaderRoute: typeof TestResultAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$testId': {
      id: '/test/$testId'
      path: '/test/$testId'
      fullPath: '/test/$testId'
      preLoaderRoute: typeof TestTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$certificateId': {
      id: '/verify/$certificateId'
      path: '/$certificateId'
      fullPath: '/verify/$certificateId'
      preLoaderRoute: typeof VerifyCertificateIdRouteImport
      parentRoute: typeof VerifyRoute
    }
    '/course/$kind/$id': {
      id: '/course/$kind/$id'
      path: '/course/$kind/$id'
      fullPath: '/course/$kind/$id'
      preLoaderRoute: typeof CourseKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intern/trial/$code': {
      id: '/intern/trial/$code'
      path: '/intern/trial/$code'
      fullPath: '/intern/trial/$code'
      preLoaderRoute: typeof InternTrialCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface VerifyRouteChildren {
  VerifyCertificateIdRoute: typeof VerifyCertificateIdRoute
}

const VerifyRouteChildren: VerifyRouteChildren = {
  VerifyCertificateIdRoute: VerifyCertificateIdRoute,
}

const VerifyRouteWithChildren =
  VerifyRoute._addFileChildren(VerifyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  JoinInternRoute: JoinInternRoute,
  JoinMentorRoute: JoinMentorRoute,
  LoginRoute: LoginRoute,
  MySessionsRoute: MySessionsRoute,
  ProfileRoute: ProfileRoute,
  PurchasesRoute: PurchasesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TicketsRoute: TicketsRoute,
  VerifyRoute: VerifyRouteWithChildren,
  AdminAuthRoute: AdminAuthRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  InternAuthRoute: InternAuthRoute,
  InternCertificateRoute: InternCertificateRoute,
  InternDashboardRoute: InternDashboardRoute,
  InternOfferLetterRoute: InternOfferLetterRoute,
  InternProfileRoute: InternProfileRoute,
  LectureSessionIdRoute: LectureSessionIdRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalTermsRoute: LegalTermsRoute,
  MentorOnboardingApplicationIdRoute: MentorOnboardingApplicationIdRoute,
  MentorProfileMentorIdRoute: MentorProfileMentorIdRoute,
  MentorSessionOfferingIdRoute: MentorSessionOfferingIdRoute,
  MentorDashboardRoute: MentorDashboardRoute,
  PromoterAuthRoute: PromoterAuthRoute,
  PromoterDashboardRoute: PromoterDashboardRoute,
  SimulatorLiveRoute: SimulatorLiveRoute,
  SoldTestIdRoute: SoldTestIdRoute,
  TestAnalysisTestIdRoute: TestAnalysisTestIdRoute,
  TestResultAttemptIdRoute: TestResultAttemptIdRoute,
  TestTestIdRoute: TestTestIdRoute,
  CourseKindIdRoute: CourseKindIdRoute,
  InternTrialCodeRoute: InternTrialCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
