/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as JoinMentorRouteImport } from './routes/join-mentor'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestTestIdRouteImport } from './routes/test.$testId'
import { Route as TestResultAttemptIdRouteImport } from './routes/test-result.$attemptId'
import { Route as TestAnalysisTestIdRouteImport } from './routes/test-analysis.$testId'
import { Route as SoldTestIdRouteImport } from './routes/sold-test.$id'
import { Route as SimulatorLiveRouteImport } from './routes/simulator/live'
import { Route as PromoterDashboardRouteImport } from './routes/promoter.dashboard'
import { Route as PromoterAuthRouteImport } from './routes/promoter.auth'
import { Route as MentorDashboardRouteImport } from './routes/mentor.dashboard'
import { Route as MentorProfileMentorIdRouteImport } from './routes/mentor-profile.$mentorId'
import { Route as MentorOnboardingApplicationIdRouteImport } from './routes/mentor-onboarding/$applicationId'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalRefundRouteImport } from './routes/legal/refund'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LectureSessionIdRouteImport } from './routes/lecture.$sessionId'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAuthRouteImport } from './routes/admin.auth'
import { Route as CourseKindIdRouteImport } from './routes/course.$kind.$id'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinMentorRoute = JoinMentorRouteImport.update({
  id: '/join-mentor',
  path: '/join-mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTestIdRoute = TestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestResultAttemptIdRoute = TestResultAttemptIdRouteImport.update({
  id: '/test-result/$attemptId',
  path: '/test-result/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestAnalysisTestIdRoute = TestAnalysisTestIdRouteImport.update({
  id: '/test-analysis/$testId',
  path: '/test-analysis/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const SoldTestIdRoute = SoldTestIdRouteImport.update({
  id: '/sold-test/$id',
  path: '/sold-test/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorLiveRoute = SimulatorLiveRouteImport.update({
  id: '/simulator/live',
  path: '/simulator/live',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoterDashboardRoute = PromoterDashboardRouteImport.update({
  id: '/promoter/dashboard',
  path: '/promoter/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoterAuthRoute = PromoterAuthRouteImport.update({
  id: '/promoter/auth',
  path: '/promoter/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorDashboardRoute = MentorDashboardRouteImport.update({
  id: '/mentor/dashboard',
  path: '/mentor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorProfileMentorIdRoute = MentorProfileMentorIdRouteImport.update({
  id: '/mentor-profile/$mentorId',
  path: '/mentor-profile/$mentorId',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorOnboardingApplicationIdRoute =
  MentorOnboardingApplicationIdRouteImport.update({
    id: '/mentor-onboarding/$applicationId',
    path: '/mentor-onboarding/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LectureSessionIdRoute = LectureSessionIdRouteImport.update({
  id: '/lecture/$sessionId',
  path: '/lecture/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/auth',
  path: '/admin/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseKindIdRoute = CourseKindIdRouteImport.update({
  id: '/course/$kind/$id',
  path: '/course/$kind/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/join-mentor': typeof JoinMentorRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/tickets': typeof TicketsRoute
  '/admin/auth': typeof AdminAuthRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/lecture/$sessionId': typeof LectureSessionIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/mentor-onboarding/$applicationId': typeof MentorOnboardingApplicationIdRoute
  '/mentor-profile/$mentorId': typeof MentorProfileMentorIdRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/promoter/auth': typeof PromoterAuthRoute
  '/promoter/dashboard': typeof PromoterDashboardRoute
  '/simulator/live': typeof SimulatorLiveRoute
  '/sold-test/$id': typeof SoldTestIdRoute
  '/test-analysis/$testId': typeof TestAnalysisTestIdRoute
  '/test-result/$attemptId': typeof TestResultAttemptIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/course/$kind/$id': typeof CourseKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/join-mentor': typeof JoinMentorRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/tickets': typeof TicketsRoute
  '/admin/auth': typeof AdminAuthRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/lecture/$sessionId': typeof LectureSessionIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/mentor-onboarding/$applicationId': typeof MentorOnboardingApplicationIdRoute
  '/mentor-profile/$mentorId': typeof MentorProfileMentorIdRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/promoter/auth': typeof PromoterAuthRoute
  '/promoter/dashboard': typeof PromoterDashboardRoute
  '/simulator/live': typeof SimulatorLiveRoute
  '/sold-test/$id': typeof SoldTestIdRoute
  '/test-analysis/$testId': typeof TestAnalysisTestIdRoute
  '/test-result/$attemptId': typeof TestResultAttemptIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/course/$kind/$id': typeof CourseKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/join-mentor': typeof JoinMentorRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/tickets': typeof TicketsRoute
  '/admin/auth': typeof AdminAuthRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/lecture/$sessionId': typeof LectureSessionIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/mentor-onboarding/$applicationId': typeof MentorOnboardingApplicationIdRoute
  '/mentor-profile/$mentorId': typeof MentorProfileMentorIdRoute
  '/mentor/dashboard': typeof MentorDashboardRoute
  '/promoter/auth': typeof PromoterAuthRoute
  '/promoter/dashboard': typeof PromoterDashboardRoute
  '/simulator/live': typeof SimulatorLiveRoute
  '/sold-test/$id': typeof SoldTestIdRoute
  '/test-analysis/$testId': typeof TestAnalysisTestIdRoute
  '/test-result/$attemptId': typeof TestResultAttemptIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/course/$kind/$id': typeof CourseKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/help'
    | '/join-mentor'
    | '/profile'
    | '/purchases'
    | '/tickets'
    | '/admin/auth'
    | '/admin/dashboard'
    | '/lecture/$sessionId'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/mentor-onboarding/$applicationId'
    | '/mentor-profile/$mentorId'
    | '/mentor/dashboard'
    | '/promoter/auth'
    | '/promoter/dashboard'
    | '/simulator/live'
    | '/sold-test/$id'
    | '/test-analysis/$testId'
    | '/test-result/$attemptId'
    | '/test/$testId'
    | '/course/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/help'
    | '/join-mentor'
    | '/profile'
    | '/purchases'
    | '/tickets'
    | '/admin/auth'
    | '/admin/dashboard'
    | '/lecture/$sessionId'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/mentor-onboarding/$applicationId'
    | '/mentor-profile/$mentorId'
    | '/mentor/dashboard'
    | '/promoter/auth'
    | '/promoter/dashboard'
    | '/simulator/live'
    | '/sold-test/$id'
    | '/test-analysis/$testId'
    | '/test-result/$attemptId'
    | '/test/$testId'
    | '/course/$kind/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/help'
    | '/join-mentor'
    | '/profile'
    | '/purchases'
    | '/tickets'
    | '/admin/auth'
    | '/admin/dashboard'
    | '/lecture/$sessionId'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/mentor-onboarding/$applicationId'
    | '/mentor-profile/$mentorId'
    | '/mentor/dashboard'
    | '/promoter/auth'
    | '/promoter/dashboard'
    | '/simulator/live'
    | '/sold-test/$id'
    | '/test-analysis/$testId'
    | '/test-result/$attemptId'
    | '/test/$testId'
    | '/course/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  JoinMentorRoute: typeof JoinMentorRoute
  ProfileRoute: typeof ProfileRoute
  PurchasesRoute: typeof PurchasesRoute
  TicketsRoute: typeof TicketsRoute
  AdminAuthRoute: typeof AdminAuthRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  LectureSessionIdRoute: typeof LectureSessionIdRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalTermsRoute: typeof LegalTermsRoute
  MentorOnboardingApplicationIdRoute: typeof MentorOnboardingApplicationIdRoute
  MentorProfileMentorIdRoute: typeof MentorProfileMentorIdRoute
  MentorDashboardRoute: typeof MentorDashboardRoute
  PromoterAuthRoute: typeof PromoterAuthRoute
  PromoterDashboardRoute: typeof PromoterDashboardRoute
  SimulatorLiveRoute: typeof SimulatorLiveRoute
  SoldTestIdRoute: typeof SoldTestIdRoute
  TestAnalysisTestIdRoute: typeof TestAnalysisTestIdRoute
  TestResultAttemptIdRoute: typeof TestResultAttemptIdRoute
  TestTestIdRoute: typeof TestTestIdRoute
  CourseKindIdRoute: typeof CourseKindIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-mentor': {
      id: '/join-mentor'
      path: '/join-mentor'
      fullPath: '/join-mentor'
      preLoaderRoute: typeof JoinMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$testId': {
      id: '/test/$testId'
      path: '/test/$testId'
      fullPath: '/test/$testId'
      preLoaderRoute: typeof TestTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-result/$attemptId': {
      id: '/test-result/$attemptId'
      path: '/test-result/$attemptId'
      fullPath: '/test-result/$attemptId'
      preLoaderRoute: typeof TestResultAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-analysis/$testId': {
      id: '/test-analysis/$testId'
      path: '/test-analysis/$testId'
      fullPath: '/test-analysis/$testId'
      preLoaderRoute: typeof TestAnalysisTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sold-test/$id': {
      id: '/sold-test/$id'
      path: '/sold-test/$id'
      fullPath: '/sold-test/$id'
      preLoaderRoute: typeof SoldTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator/live': {
      id: '/simulator/live'
      path: '/simulator/live'
      fullPath: '/simulator/live'
      preLoaderRoute: typeof SimulatorLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promoter/dashboard': {
      id: '/promoter/dashboard'
      path: '/promoter/dashboard'
      fullPath: '/promoter/dashboard'
      preLoaderRoute: typeof PromoterDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promoter/auth': {
      id: '/promoter/auth'
      path: '/promoter/auth'
      fullPath: '/promoter/auth'
      preLoaderRoute: typeof PromoterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor/dashboard': {
      id: '/mentor/dashboard'
      path: '/mentor/dashboard'
      fullPath: '/mentor/dashboard'
      preLoaderRoute: typeof MentorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-profile/$mentorId': {
      id: '/mentor-profile/$mentorId'
      path: '/mentor-profile/$mentorId'
      fullPath: '/mentor-profile/$mentorId'
      preLoaderRoute: typeof MentorProfileMentorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-onboarding/$applicationId': {
      id: '/mentor-onboarding/$applicationId'
      path: '/mentor-onboarding/$applicationId'
      fullPath: '/mentor-onboarding/$applicationId'
      preLoaderRoute: typeof MentorOnboardingApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecture/$sessionId': {
      id: '/lecture/$sessionId'
      path: '/lecture/$sessionId'
      fullPath: '/lecture/$sessionId'
      preLoaderRoute: typeof LectureSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auth': {
      id: '/admin/auth'
      path: '/admin/auth'
      fullPath: '/admin/auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$kind/$id': {
      id: '/course/$kind/$id'
      path: '/course/$kind/$id'
      fullPath: '/course/$kind/$id'
      preLoaderRoute: typeof CourseKindIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  JoinMentorRoute: JoinMentorRoute,
  ProfileRoute: ProfileRoute,
  PurchasesRoute: PurchasesRoute,
  TicketsRoute: TicketsRoute,
  AdminAuthRoute: AdminAuthRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  LectureSessionIdRoute: LectureSessionIdRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalTermsRoute: LegalTermsRoute,
  MentorOnboardingApplicationIdRoute: MentorOnboardingApplicationIdRoute,
  MentorProfileMentorIdRoute: MentorProfileMentorIdRoute,
  MentorDashboardRoute: MentorDashboardRoute,
  PromoterAuthRoute: PromoterAuthRoute,
  PromoterDashboardRoute: PromoterDashboardRoute,
  SimulatorLiveRoute: SimulatorLiveRoute,
  SoldTestIdRoute: SoldTestIdRoute,
  TestAnalysisTestIdRoute: TestAnalysisTestIdRoute,
  TestResultAttemptIdRoute: TestResultAttemptIdRoute,
  TestTestIdRoute: TestTestIdRoute,
  CourseKindIdRoute: CourseKindIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
